# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

header:
  comment: on-failure
  license:
    spdx-id: Apache-2.0
    copyright-owner: SUSE LLC
    software-name: supportutils-plugin-trento
    content: |
      SPDX-FileCopyrightText: SUSE LLC
      SPDX-License-Identifier: Apache-2.0
  paths-ignore:
    - "**/*.adoc"
    - ".github/dependabot.yml"
    - ".tool-versions"
    - "LICENSE"
    - "VERSION"
    - "packaging/suse/supportutils-plugin-trento/trento"
    - "packaging/suse/supportutils-plugin-trento/supportutils-plugin-trento.spec"
