# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

name: Continuous Integration

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "VERSION"
      - "CHANGELOG.md"
  pull_request:
    paths-ignore:
      - "VERSION"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v5

      - name: Read .tool-versions
        id: tool-versions
        uses: endorama/asdf-parse-tool-versions@afbfa92e56234f29b1e82314f50c3d1244285f60 # v1.3.4

      - name: Install shfmt
        run: |
          version="v${{ env.SHFMT_VERSION }}"
          wget https://github.com/mvdan/sh/releases/download/${version}/shfmt_${version}_linux_amd64
          chmod +x shfmt_${version}_linux_amd64
          sudo mv shfmt_${version}_linux_amd64 /usr/local/bin/shfmt

      - name: Check formatting
        run: make fmt-check

      - name: Install ShellCheck
        run: |
          set -e
          version="${{ env.SHELLCHECK_VERSION }}"
          ARCH=$(uname -m)
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          wget -qO shellcheck.tar.xz https://github.com/koalaman/shellcheck/releases/download/v${version}/shellcheck-v${version}.${OS}.${ARCH}.tar.xz
          tar -xf shellcheck.tar.xz
          sudo mv shellcheck-v${version} /usr/local/share/shellcheck
          sudo ln -sf /usr/local/share/shellcheck/shellcheck /usr/local/bin/shellcheck

      - name: Check for lint issues
        run: make lint

      - name: Check license headers
        uses: apache/skywalking-eyes/header@61275cc80d0798a405cb070f7d3a8aaf7cf2c2c1 # v0.8.0

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v5

      - name: Read .tool-versions
        id: tool-versions
        uses: endorama/asdf-parse-tool-versions@afbfa92e56234f29b1e82314f50c3d1244285f60 # v1.3.4

      - name: Setup BATS
        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1
        with:
          bats-version: ${{ env.BATS_VERSION }}

      - name: Run tests
        run: |
          bats -r ./test

  obs-sync:
    name: OBS sync
    if: fromJSON(vars.OBS_ENABLED) && github.event_name == 'push'
    uses: trento-project/.github/.github/workflows/obs-sync.yaml@7ea6a8a1c3ed8a1f2185328219be4a724dd3686e # v1.8.0
    needs:
      - static-analysis
      - test
    with:
      obs_project: ${{ vars.OBS_PROJECT_ROLLING }}
      obs_package: ${{ vars.OBS_PACKAGE }}
    secrets:
      gh_token: ${{ secrets.TRENTOBOT_GH_PAT }}
      obs_user: ${{ secrets.OBS_USER }}
      obs_pass: ${{ secrets.OBS_PASS }}
      obs_ssh_key: ${{ secrets.OBS_SSH_KEY }}
