name: Continuous Integration

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Read .tool-versions
        id: tool-versions
        uses: endorama/asdf-parse-tool-versions@afbfa92e56234f29b1e82314f50c3d1244285f60 # v1.3.4

      - name: Install shfmt
        run: |
          version="v${{ env.SHFMT_VERSION }}"
          wget https://github.com/mvdan/sh/releases/download/${version}/shfmt_${version}_linux_amd64
          chmod +x shfmt_${version}_linux_amd64
          sudo mv shfmt_${version}_linux_amd64 /usr/local/bin/shfmt

      - name: Check formatting
        run: make fmt-check

      - name: Install ShellCheck
        run: |
          set -e 
          version="${{ env.SHELLCHECK_VERSION }}"
          ARCH=$(uname -m)
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          wget -qO shellcheck.tar.xz https://github.com/koalaman/shellcheck/releases/download/v${version}/shellcheck-v${version}.${OS}.${ARCH}.tar.xz
          tar -xf shellcheck.tar.xz
          sudo mv shellcheck-v${version} /usr/local/share/shellcheck
          sudo ln -sf /usr/local/share/shellcheck/shellcheck /usr/local/bin/shellcheck
      - name: Check for lint issues
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Read .tool-versions
        id: tool-versions
        uses: endorama/asdf-parse-tool-versions@afbfa92e56234f29b1e82314f50c3d1244285f60 # v1.3.4

      - name: Setup BATS
        uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1
        with:
          bats-version: ${{ env.BATS_VERSION }}

      - name: Run tests
        run: |
          bats -r ./test
