name: Continuous Integration

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Read .tool-versions
        id: tool-versions
        uses: endorama/asdf-parse-tool-versions@v1.3.4

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: ${{ env.BATS_VERSION }}

      - name: Run tests
        run: |
          bats -r ./test
